### PR TITLE
604 bug

### PR DESCRIPTION
**Pull request by shivang2311**
made changes as told @Oliver2049 in previous branch, which is 604-bug-fix. i created new one because in that one i got some unexpected errors. So can you please review this one? Thanks!!

### CODE REVIEW

**Comment by shivang2311** [comment]
The new code introduces significant improvements for code standardization. It adds Advanced and Custom modes, allowing for more flexibility in configuration. The Advanced mode includes additional options such as verbosity and disabling beacons, while the Custom mode supports custom scripts. The interface is updated to include these new options, and error handling has been enhanced. Additionally, the layout has been improved with better organization, tooltips, and command previews, making the code more user-friendly and adhering to the style guide for readability and maintainability.

**Comment by shivang2311** [comment]
In the SearchSploit task, I focused on fixing a baseline bug by updating the component according to a predefined checklist. This included standardizing the code, removing unnecessary imports, and ensuring proper use of React hooks and components like LoadingOverlayAndCancelButtonPkexec. I also followed the project's style guide to ensure consistency.

**Comment by Oliver2049** [comment]
> In the SearchSploit task, I focused on fixing a baseline bug by updating the component according to a predefined checklist. This included standardizing the code, removing unnecessary imports, and ensuring proper use of React hooks and components like LoadingOverlayAndCancelButtonPkexec. I also followed the project's style guide to ensure consistency.

Thanks, @shivang2311
I will check and provide feedback to you as soon as possible. Thanks.
Regards,
Oliver

**Comment by Oliver2049** [comment]
Hi @shivang2311 ,
Well sadly for this one, you will have to remove the py file as well before I can review the pull request.
Regards,
Oliver

**Pull request closed without merging**
