### PR TITLE
Fix DirbTool Command Options for Case Insensitive, Print Location Header, and HTTP Code Errors

### PR DESCRIPTION
**Pull request by Harshpatel24197**
This PR resolves issues #477 in which the case insensitive error, print location header error and ignore responses with this HTTP code error show wrong responses because incorrect commands were written.

**1**- Case Insensitive Error- Fixed the issue where the incorrect command -S was being used instead of -I for case-insensitive search. Removed the extraneous boolean value appended to the command.

**2**- Print Location Header Error- Corrected the command from -s to -L to print the 'Location' header when found. Removed the unnecessary boolean value from the command.

**3**- Ignore Responses with this HTTP Code Error- Updated the command from -t to -N for ignoring responses with a specific HTTP code.

**4**- Ran yarn run style to identify and fix code formatting issues.
    Ran npx prettier --write to ensure consistent code formatting across affected files.

Thanks
Harsh and Shubham

### CODE REVIEW

**Review by bradleybogg — CHANGES_REQUESTED** [review]
Please correct errors identified in the CI testing.
This requires you to run yarn style.

How to fix:
Run : yarn run style in DDT terminal

You should see the files that cause the build to fail.

Run : npx prettier --write <filepath>

Please also consider the naming of your pull request.

**Comment by JiatengTao** [comment]
> Please correct errors identified in the CI testing. This requires you to run yarn style.
> 
> How to fix: Run : yarn run style in DDT terminal
> 
> You should see the files that cause the build to fail.
> 
> Run : npx prettier --write
> 
> Please also consider the naming of your pull request.

I think a good option is to run "npx prettier -- write [file_name]" to all files changed.

**Comment by JiatengTao** [comment]
Good work, please use squash and merge option to make sure the commit history is clean.

**Review by bradleybogg — DISMISSED** [review]

**Comment by bradleybogg** [comment]
Hi @Harshpatel24197,

When creating your branch please use the convention we have specified. This is best completed by creating it from the github issue.

Kind Regards,

Bradley

**Review by bradleybogg — COMMENTED** [review]
@gangamarx Please proceed with applicatin testing.

**Comment by zkkok** [comment]
Hi @Harshpatel24197,

Functionality testing has been conducted. Here are the details:
[Functionalty Test(Dirb).pdf](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/files/15156642/Functionalty.Test.Dirb.pdf)


The tool works fine but here are some things you need to change before merging:
1. Remove “required” for wordlists field (wordlists is a optional parameter)
2. Remove “-v” when checking “advanced mode” (Test#2)
3. Add checks so that when “advanced mode” is disabled the parameters under it would be 
disabled at the same time

**Comment by chandelshubham63** [comment]
@zkkok @bradleybogg   made the required requested changes and tested for proper functionality.

**Review by michaeljpigott — APPROVED** [review]
Hi there

I have re-done application testing and found:

- the wordlist field is no longer a required field. 
- there is no -v field when checking advanced mode
- the advanced parameters are removed once advanced mode is turned off. 

Well done. 

Kind regards

Michael

**Pull request merged**
