### PR TITLE
625 feature request handleprocessdata improvement

### PR DESCRIPTION
**Pull request by michaeljpigott**
### Pull request description

This pull request fixes issue #625 whereby DDT cannot handle terminal output that is using ANSI colour stylings. 

### Changes made

The fix was to simple add a line of code in CommandHelper.ts that uses regex in the replace method to look for any ANSI colour stylings in the data and replace them with an empty string.

### CODE REVIEW

**Review by bradleybogg — CHANGES_REQUESTED** [review]
Failed Application Testing - Received escaped characters on Aircrack-Ng

**Comment by michaeljpigott** [comment]
Hi, I adjusted the regex in CommandHelper.ts so it strips out the VT100 escape codes that were appearing in the Aircrack-ng output. I tested on Aircrack-ng, Arjun and WPScan and they weren't showing any escape characters.

**Comment by michaeljpigott** [comment]
@zkkok can you please do some application testing on this pull request? Relevant tools that have escaped characters are Aircrack-ng, WhatWeb, Arjun and WPScan.

**Review by zkkok — APPROVED** [review]
Hi @michaeljpigott, i have done some testing, doesn't seem like the components you mentioned generated any escaped characters with the new implementation.

[Functionality Testing(HandleProcessData).pdf](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/files/15286108/Functionality.Testing.HandleProcessData.pdf)

**Comment by michaeljpigott** [comment]
Thank you @zkkok for testing.

**Pull request merged**
