### PR TITLE
702 bug baseline arjun

### PR DESCRIPTION
**Pull request by michaeljpigott**
Hi, 

This pull request is to baseline Arjun. The code has been updated so Arjun is using the three-tabbed format. I have also updated the description and steps. 

Please note that issue #706 is affecting Arjun and the tool cannot be run. 

Kind regards

Michael

### CODE REVIEW

**Comment by michaeljpigott** [comment]
Hi @namanbkshi, can you please review my pull request?

**Review by namanbkshi — COMMENTED** [review]
Hi @michaeljpigott ! Code looks great. 

I have just have one suggestion:

-Interface FormValues can be changed to interface FormValuesType { ....}  for better consistency.

**Comment by michaeljpigott** [comment]
Thank you for checking @namanbkshi. I have made that change. Can you please review again?

**Comment by namanbkshi** [comment]
Looks good to me @michaeljpigott !

**Review by namanbkshi — COMMENTED** [review]
Looks good to me @michaeljpigott !

**Review by namanbkshi — APPROVED** [review]

**Pull request merged**
