### PR TITLE
472 file uploader

### PR DESCRIPTION
**Pull request by bradleybogg**
Pull Request Title:

Feature: Implement File Upload Functionality for DDT

Pull Request Description:

This pull request introduces a crucial feature to DDT, enabling users to upload files directly within the application interface. This functionality becomes necessary due to the restricted access to directories from which the application can read for security.

Changes Made:

Added File Upload Capability: Implemented the necessary frontend components to allow users to upload files.

Backend Integration: Established backend scripts in rust to handle file uploads securely.

File Storage: Implemented a mechanism to store uploaded files in a known location accessible to the application.

Amended rainbowcrack to allow upload of a file.

Uplift mantine to 5.10.5 (latest version 5)

### CODE REVIEW

**Comment by JiatengTao** [comment]
Looks like Git Action is still using Yarn 1.22, the mitigation method doesn't work, wait for further investigation

**Comment by JiatengTao** [comment]
FYI, steps required to migrate the project from yarn 1.xx to 4.xx https://yarnpkg.com/migration/guide

Better to use 1.xx in local env to make this change.

**Comment by michaeljpigott** [comment]
> Not sure what's causing this check to fail, any pointers?

Hi @slpysiren, my research tells me the issue is being caused by the GitHub CI running an older version of Yarn. I have tried updating the ci.yml file but no luck. :-( 

I might post on the group chat to see any GitHub guns can help. 

image

**Comment by michaeljpigott** [comment]
Bummer!! I will raise this issue at our weekly team meeting next week.

**Comment by michaeljpigott** [comment]
@slpysiren can I close this pull request now that it has been replaced by #836?

**Comment by slpysiren** [comment]
@michaeljpigott probably best yes.

**Comment by michaeljpigott** [comment]
Closing this pull request because it has been replaced by #836

**Pull request closed without merging**
