### PR TITLE
made some modification on logo to fit both the dark mode and light mode

### PR DESCRIPTION
**Pull request by uppowerdo**
This pull request addresses the following issues:
	1.	Adjusted the logo to fit both dark mode and light mode.
	2.	Centered the logo for proper alignment.
	3.	Fixed the issue where clicking the logo would switch modes.

### CODE REVIEW

**Comment by uppowerdo** [comment]
This pull request also fix the bug "Clicking on DDT logo causing flash briefly #868"

**Review by michaeljpigott — CHANGES_REQUESTED** [review]
Hi @uppowerdo 

I am getting a 404 on the image when opening DDT. I am thinking you probably need to commit the new images. 😉

image

Kind regards 

Michael

**Comment by uppowerdo** [comment]
Sorry, I forgot. It is added to the root folder now.

**Review by michaeljpigott — APPROVED** [review]
Hi @uppowerdo 

This change looks good. It is slightly difficult to read the blue text in light mode, but otherwise all good. I approve. 

Kind regards

Michael

**Pull request merged**
