### PR TITLE
This is the solution for the bug LIBEGL Warning.

### PR DESCRIPTION
**Pull request by abasb123**
This pull request addresses the issue of the "Failed to Create DRI2 Screen" error, which occurs when running the Deakin Detonator Toolkit (DDT) on virtual machines, particularly when using Kali Linux on a Windows 10 host via VirtualBox.

### CODE REVIEW

**Comment by abasb123** [comment]
Hi @michaeljpigott , can you please approve this pull request. Kind regards.

**Comment by michaeljpigott** [comment]
Hi @abasb123 can you explain a bit more about how this script is meant to be used? For example, are we meant to run it from the command line?

**Comment by abasb123** [comment]
> Hi @abasb123 can you explain a bit more about how this script is meant to be used? For example, are we meant to run it from the command line?

Yes we are meant to run it on Kali Linux command line to fix the issue. It will ensure all the drives are working correctly and install required libraries to make the Deakin detonator toolkit run smoothly. By running these commands will help to fix any issues related to Linux LIBGL drivers environment and Direct Rendering Infrastructure (DRI) problems.

**Comment by michaeljpigott** [comment]
Hi @abasb123 

It does not appear to work for me:

image

**Comment by abasb123** [comment]
> Hi @abasb123
> 
> It does not appear to work for me:
> 
> image

Hi @michaeljpigott , The following command should be run one by one to fix the issue. The python file includes the commands which can be run on command line and its description for each command.
Screenshot 2024-08-31 152229
Screenshot 2024-08-31 152539

**Comment by michaeljpigott** [comment]
Hi @abasb123 

Okay, if it is not intended to be run as a Python file, then I recommend adding this as a .md file. @github4phil started a new initiative today where there is a documentation folder within the codebase where you can information for developers. I recommend: 

1. Update your branch with the [changes from main](https://stackoverflow.com/questions/41045548/merging-changes-from-master-into-my-branch). 
2. Change your Python script into a markdown file and save it to the developer_information folder. 
3. Push the changes back to GitHub. 

Let me know if you have any questions. :-)

**Comment by abasb123** [comment]
> Hi @abasb123
> 
> Okay, if it is not intended to be run as a Python file, then I recommend adding this as a .md file. @github4phil started a new initiative today where there is a documentation folder within the codebase where you can information for developers. I recommend:
> 
> 1. Update your branch with the [changes from main](https://stackoverflow.com/questions/41045548/merging-changes-from-master-into-my-branch).
> 2. Change your Python script into a markdown file and save it to the developer_information folder.
> 3. Push the changes back to GitHub.
> 
> Let me know if you have any questions. :-)

Hi @michaeljpigott ,
Do I have to create a new pull request for that.
Kind regards.
Abbas

**Comment by michaeljpigott** [comment]
Hi @abasb123 you do not need to create a new pull request - you can make your changes to the branch and it will automatically update the pull request. 

Is there a particular why you want to merged this into _705-bug-libegl-warning-egl-failed-to-create-dri2-screen_ instead of _main_? 

Kind regards

Michael

**Comment by abasb123** [comment]
Hi @michaeljpigott , 
No, I will change it to main.
Kind regards,
Abbas.

**Comment by michaeljpigott** [comment]
Hi @abasb123 can you please confirm that we can close this pull request because it has been superseded by another pull request? 

Kind regards

Michael

**Comment by abasb123** [comment]
Hi @michaeljpigott , 
Yes, you can close this pull request. 
Kind regards,
Abbas.

**Comment by michaeljpigott** [comment]
Closing this pull request as it is a duplicate.

**Pull request closed without merging**
