### PR TITLE
220586039 installation readme.md

### PR DESCRIPTION
**Pull request by github4phil**
New installation script, updating readme accordingly

### CODE REVIEW

**Review by michaeljpigott — COMMENTED** [review]
Hi @github4phil 

When I try to run the installation script, I am getting this message in the terminal:

image

Michael

**Comment by github4phil** [comment]
The link wont work when this branch isn't merged into master, once the branch is merged the link will work. If the link worked now it wouldn't work when merged.

I do however need to make some changes to this branch - namely this is a script that **runs** rather than **installs**  the application. Which are fundamentally different things. Action is required by me.

**Comment by github4phil** [comment]
The link wont work when this branch isn't merged into master, once the branch is merged the link will work. If the link worked now it wouldn't work when merged.

**Review by michaeljpigott — APPROVED** [review]
Thank you @github4phil. It looks good. I appreciate the descriptive commits.

**Pull request merged**
