### PR TITLE
Merge pull request #754 from Hardhat-Enterprises/main

### PR DESCRIPTION
**Pull request by abasb123**
libEGL warning egl : failed to create dri2 screen #705 bug fixed.
The  bug i found was related to "failed to create dri2 screen" typically indicates an issue related to the Direct Rendering Infrastructure (DRI), which is part of the graphics stack on Linux. This problem can occur for various reasons, such as driver issues, missing libraries, or incorrect configurations.

### CODE REVIEW

**Comment by michaeljpigott** [comment]
Hi @abasb123, there does not appear any changes to check in this pull request? 

Kind regards

Michael

**Comment by michaeljpigott** [comment]
Hi @abasb123 can you please confirm that I can close this pull request since it has been replaced by another one?

**Comment by abasb123** [comment]
> Hi @abasb123 can you please confirm that I can close this pull request since it has been replaced by another one?

Yes, you can close it.

**Comment by michaeljpigott** [comment]
Closing pull request because it is a duplicate.

**Pull request closed without merging**
