### PR TITLE
577 bug fix baseline crackmapexec

### PR DESCRIPTION
**Pull request by niloy1997**
Made the changes as told

### CODE REVIEW

**Comment by niloy1997** [comment]
Made the changes as told

**Comment by connorwjordan** [comment]
There are no changes made to the crackmapexac.tsx file that needs to fit the baseline checklist, as the last commit has reverted all changes back into its current state in the main branch. There are also 4 files deleted in this request that should not be changed.

**Comment by Siddh2001** [comment]
@niloy1997 you might just have to delete the 4 unwanted files you're not working on and then push the code
the simplest way to do this is by creating a newer branch if you're having issues, if you do so please let us know so that we can delete this one so that the GIT remains organised. Thanks

**Comment by michaeljpigott** [comment]
Added the on hold label while the files get sorted out for this pull request.

**Comment by niloy1997** [comment]
Please delete this one as I have created a newer branch, Thanks

**Pull request closed without merging**
