### PR TITLE
Vulscan Tool Completed

### PR DESCRIPTION
**Pull request by tjmat1**
Added completed Vulscan Tool
Reference Added

### CODE REVIEW

**Review by Huskehhh — CHANGES_REQUESTED** [review]
The code looks great. I am however unable to execute any of the scripts, see below image.

image

**Comment by tjmat1** [comment]
Hi Jordan,

The vulscan module requires manual installation into the scripts folder of the Nmap installation on the user's system (Instructions on https://github.com/scipag/vulscan). 

Could we add this as a requirement before the tool is used? Or did we need to add the installation into the project code itself (I wasn't sure if this was necessary?).

Thanks :)

**Review by tjmat1 — COMMENTED** [review]
Please refer to comment above :)

**Comment by Huskehhh** [comment]
> Hi Jordan,
> 
> The vulscan module requires manual installation into the scripts folder of the Nmap installation on the user's system (Instructions on https://github.com/scipag/vulscan).
> 
> Could we add this as a requirement before the tool is used? Or did we need to add the installation into the project code itself (I wasn't sure if this was necessary?).
> 
> Thanks :)

Good call. We should look at doing this in the `install_dependencies.sh` script

**Pull request closed without merging**
