### PR TITLE
Baseline Netcat #598

### PR DESCRIPTION
**Pull request by Oliver2049**
* Added required imports
* Added the appropriate docstring to the functions and interface
* Changed the state variables to camelCase
* Added inline comments to all react hooks and to all component constant
* Removed the Userguide(title,description_userguide) in Stack as it is no longer required
* Added the steps for user guide in component description
* Add required component state variables
* Added sourceLink and updated it with the appropriate link
* Added empty string in tutorial
* Fixed grammar issues
* Added the function handleSaveComplete with appropriate comments and docstring                 
* Added the render component  for user guide which was not there in the code

### CODE REVIEW

**Comment by michaeljpigott** [comment]
Hi @Oliver2049 

Is this a baseline task? You need to link this pull request with the relevant GitHub issue. Please update the title of this pull request to be more reflective of what changes have been made. 

Also, your pull request is failing the GitHub CI check, so you need to resolve this before I review the code. 

If this is a baseline job, then you only need to update the netcat.tsx file. There is a document in our PT-GUI channel on Teams, which will tell you how to remove the extra files from your pull request. 

Please action the above items before I review the code. 

Kind regards

Michael

**Comment by Oliver2049** [comment]
> Hi @Oliver2049
> 
> Is this a baseline task? You need to link this pull request with the relevant GitHub issue. Please update the title of this pull request to be more reflective of what changes have been made.
> 
> Also, your pull request is failing the GitHub CI check, so you need to resolve this before I review the code.
> 
> If this is a baseline job, then you only need to update the netcat.tsx file. There is a document in our PT-GUI channel on Teams, which will tell you how to remove the extra files from your pull request.
> 
> Please action the above items before I review the code.
> 
> Kind regards
> 
> Michael

Hi Michael, 
I did revert the changes of yarn.lock but somehow it still doesn't pass the CI

**Comment by Oliver2049** [comment]
Hi @michaeljpigott 
Can you check if the CI works?

**Comment by michaeljpigott** [comment]
Hi @Oliver2049 

I think you will need to remove the yarn.lock file from your pull request completely. I will send you instructions for how to do that in Teams. 

Thank you for renaming the pull request. 

Kind regards

Michael

**Pull request closed without merging**
