### PR TITLE
Userguide arjun tool 

### PR DESCRIPTION
**Pull request by Abhijeet-97**
Output file was not working so improved the tool by correcting the prop name.

### CODE REVIEW

**Review by Phaellynn — CHANGES_REQUESTED** [review]
Arjuntool saves to an output file now, so the original issue is fixed, but it now seems to have TWO fields requesting the filename. 
Completing the first output file field (Optional Json output file) DOES NOT save the output file to disk.
Completing the second output file field (Output filename) and pressing the 'Save Output To File' button DOES save the file to disk.
I recommend removing the first field altogether.
Screenshot 2023-12-04 161205
Screenshot 2023-12-04 161320

**Review by Sakada-lim — CHANGES_REQUESTED** [review]
The updated code has part of the code for Dirbtools. Please review your change and revert it back before doing another commit.

**Comment by Abhijeet-97** [comment]
I reviewed the code and made the changes by removing the first output field. Now there is only one field to save the Output File. While testing the code was working Fine.

**Review by Phaellynn — APPROVED** [review]
Branch: userguideArjuntool 
Tool passes functionality test:
- Tool now has only one field for writing a file name for saving output to disk.
- Tool successfully saves the output to a file on the hard disk.
Screenshot 2023-12-09 162516

**Comment by Abhijeet-97** [comment]
I have created the #PR449 for the same. Can you please review it and approve the merge request.

**Review by Sakada-lim — APPROVED** [review]

**Pull request merged**
