### PR TITLE
296 cancel operation ddt wide rollout 1

### PR DESCRIPTION
**Pull request by anjojoseph**
Hi Brad/Team,
I have implemented cancel operation for Netcat tool.
Run npx prettier command.
Kindly verify and merge.
Thank you

### CODE REVIEW

**Review by bradleybogg — CHANGES_REQUESTED** [review]
Hi @anjojoseph 

Please rectify the merge conflict. Can you also please update us with what is meant to be happening here?

What is the scope of your change. You have made all changes in a single commit and the component doesnt conform to our baselining standards.

Thank you!

**Comment by anjojoseph** [comment]
Hi Brad,
I worked on Hardhat-Enterprises/Deakin-Detonator-Toolkit/tree/296-cancel-operation-ddt-wide-rollout-1/src/components/Netcat
/Netcat.tsx , file to implement cancel operation, as per of  Feature Request: Cancel Operation (https://trello.com/c/rQLOilvH)
Updating all tool’s that use CommandHelper.runCommand() to use CommandHelper.runCommandGetPidAndOutput() and updating associated logic to enable a tool’s execution to be cancelled by the user.

I believe the conflict happened as the same file src/components/Netcat/Netcat.tsx has been modified on the main barnch after New branch for Netcat improvements and formatted #530 has been approved.
Currently I work to resolve these conflicts and implement cancel operation.
Thank you

**Comment by anjojoseph** [comment]
Awaiting Bas to merge his branch to main as he works on Netcat.tsx
I will start to resolve these conflicts after this.

**Comment by anjojoseph** [comment]
Latest netcat tool uses CommandHelper.runCommandGetPidAndOutput() function hence stopped working on netcat tool. for cancel operation

**Pull request closed without merging**
