### PR TITLE
513-feature-request-code-standardization

### PR DESCRIPTION
**Pull request by shivang2311**
enhance the Basic, Advanced, and Custom modes

### CODE REVIEW

**Comment by rng4302** [comment]
Hello Shivang,
I am happy to review this PR but may I know what problem are you trying to solve in this pull?

**Comment by shivang2311** [comment]
The new code introduces significant improvements for code standardization. It adds Advanced and Custom modes, allowing for more flexibility in configuration. The Advanced mode includes additional options such as verbosity and disabling beacons, while the Custom mode supports custom scripts. The interface is updated to include these new options, and error handling has been enhanced. Additionally, the layout has been improved with better organization, tooltips, and command previews, making the code more user-friendly and adhering to the style guide for readability and maintainability.

**Comment by michaeljpigott** [comment]
So @shivang2311 so are improvements for the Airbase-NG tool? In that case, can you please remove zerologon_tester.py as a commit. I will send you the instructions in Teams. 

Kind regards

Michael

**Comment by michaeljpigott** [comment]
Placing pull request on hold while we wait for zerologon_tester.py to be removed as a commit.

**Pull request closed without merging**
