### PR TITLE
Urlsnarf + Hydra improvements

### PR DESCRIPTION
**Pull request by zinchenkoboris**
This includes:
- a new recon tool - Urlsnarf
- several sizeable upgrades to my earlier tool - Hydra. Better UI, better interactivity of the page

### CODE REVIEW

**Review by PurpleSn0w — CHANGES_REQUESTED** [review]
Hydra tool has GUI layout issues.
UrlSnarf give an error "No such file or directory (os error 2)" using both listener settings.

**Comment by zinchenkoboris** [comment]
fix in progress

**Review by Huskehhh — APPROVED** [review]

**Comment by Huskehhh** [comment]
@PurpleSn0w fixed the dep issue. Requires the DDT application to be run as root

**Comment by Huskehhh** [comment]
@zinchenkoboris would be good to get a reference added, too!

**Comment by zinchenkoboris** [comment]
> @zinchenkoboris would be good to get a reference added, too!

what kind of reference?

**Review by PurpleSn0w — APPROVED** [review]

**Pull request merged**
