### PR TITLE
Fixed Installation Modal Pop-Up Issue

### PR DESCRIPTION
**Pull request by chyrm**
- Fixed the unnecessary pop-up of the installation modal.

### CODE REVIEW

**Review by basoreeper3007 — APPROVED** [review]
Amazing! Good work!

**Comment by basoreeper3007** [comment]
This was application tested by me.

**Review by michaeljpigott — CHANGES_REQUESTED** [review]
Hi @chyrm 

This is good, but I reckon there's a way you can update the code without using Bash. 

I recommend instead of updating CommandAvailability.ts, you can update tauri.config.json and allow which as a scoped command. 

Kind regards

Michael

**Comment by michaeljpigott** [comment]
Hi @chyrm 

Changed the label to "Awaiting Assignee Update" because I am waiting to hear from you about my proposed change. 

Kind regards

Michael

**Comment by chyrm** [comment]
Hi @michaeljpigott , Your solution seems much better and easy. I have now updatde the Tauri config file to change the scope of the "which" command.

**Review by basoreeper3007 — APPROVED** [review]
Great Job!

**Review by michaeljpigott — APPROVED** [review]
Thanks @chyrm, I approve this pull request too.

**Pull request merged**
